services:
  web:
    image: nginx:latest
    ports:
      - "8078:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./docker/postgres/pg_hba.conf:/var/lib/postgresql/18/docker/pg_hba.conf
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: