# https://taskfile.dev

version: '3'

vars:
  DOCKER_COMPOSE: "docker-compose.local.yaml"
  DOCKER_COMPOSE_DEPLOY: "docker-compose.deploy.yaml"

tasks:
  composer:
    desc: example= task composer -- i
    cmds:
      - docker compose --file {{.DOCKER_COMPOSE}} exec app composer {{.CLI_ARGS}}
    silent: true

  setup:
    desc: Use on first launch
    silent: true
    cmds:
      - cp -n .env.example .env
      - docker compose --file {{.DOCKER_COMPOSE}} up --build -d --force-recreate --remove-orphans
      - task: composer
        vars: { CLI_ARGS: 'install' }

  up:
    silent: true
    cmds:
      - docker compose --file {{.DOCKER_COMPOSE}} up -d --force-recreate

  down:
    silent: true
    cmds:
      - docker compose --file {{.DOCKER_COMPOSE}} down

  deploy:
    silent: true
    cmds:
    - task: setup
      vars: { DOCKER_COMPOSE: '{{.DOCKER_COMPOSE_DEPLOY}}' }
    - echo 'Project is deployed successfully'

  undeploy:
    silent: true
    cmds:
      - task: down
        vars: { DOCKER_COMPOSE: '{{.DOCKER_COMPOSE_DEPLOY}}' }
      - echo 'Project is undeploy successfully'